# Generated by Django 5.1.1 on 2024-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="post_images"),
        ),
    ]
